### ISSUE TITLE
App Crashes when .show() is called in onClick event

### ISSUE THREAD

**Issue by BrandonQuintanilla** [fraggjkee/sms-confirmation-view#1]
Error when calling a dialogFragment from a clickEvent

![image](https://user-images.githubusercontent.com/48459532/108171741-f8cf3a80-70c9-11eb-8f68-bce489812a11.png)

Actually it works when the method showDialog() is called from Activity.onCreate() but app crashes when showDialog() method is called from a onClickListener event.  I´m using ViewBinding.

**Dialog class that contains sms-confirmation-view:**
```

class RecuperarContraseniaDialog : DialogFragment(), View.OnClickListener {
    private var _binding: DialogRecuperarContraseniaBinding? = null
    private val binding get() = _binding!!
    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        _binding = DialogRecuperarContraseniaBinding.inflate(LayoutInflater.from(context))
        return AlertDialog.Builder(requireActivity()).setView(binding.root).create(
    }
    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
    override fun onClick(view: View) {
        when (view.id) {
            R.id.btn_close -> {
                dismiss()
            }
            R.id.btn_registrarse_done -> {
                dismiss()
            }
        }
    }
}

```

**Dialog XML:**
```

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@drawable/dialog_rounded_corners"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    android:paddingBottom="15dp">
    <ImageButton
        android:id="@+id/btn_close"
        android:layout_width="25dp"
        android:layout_height="25dp"
        android:layout_marginTop="10dp"
        android:layout_marginEnd="10dp"
        android:background="@drawable/cerrar_dialog"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
    <TextView
        android:id="@+id/txv_descr"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:paddingHorizontal="20dp"
        android:paddingVertical="5dp"
        android:text="Ingrese el código enviado a su correo electrónico para restablecer su contraseña"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/btn_close" />
    <com.fraggjkee.smsconfirmationview.SmsConfirmationView
        android:id="@+id/code_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="15dp"
        android:background="@color/white"
        android:gravity="center"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/txv_descr"
        app:scv_codeLength="4"
        app:scv_symbolBackgroundColor="@color/white"
        app:scv_symbolBorderColor="@color/md_grey_400"
        app:scv_symbolBorderCornerRadius="6dp"
        app:scv_symbolBorderWidth="2dp"
        app:scv_symbolHeight="50dp"
        app:scv_symbolTextSize="27sp"
        app:scv_symbolWidth="45dp"
        app:scv_symbolsSpacing="5dp" />
    <Space
        android:id="@+id/space_one"
        android:layout_width="match_parent"
        android:layout_height="20dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/code_view" />
    <androidx.appcompat.widget.AppCompatButton
        android:id="@+id/btn_registrarse_done"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/primary_btn_style"
        android:paddingHorizontal="30dp"
        android:text="Restablecer su contraseña"
        android:textAllCaps="false"
        android:textColor="@color/md_white_1000"
        android:textSize="14dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/space_one" />
</androidx.constraintlayout.widget.ConstraintLayout>

```
///////////////////////////////////////////////////////////////////////////////////////
**Activity who is performing the showDialog() method:**
```

class LoginActivity : AppCompatActivity(), View.OnClickListener {
    private lateinit var binding: ActivityLoginBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityLoginBinding.inflate(layoutInflater)
        setContentView(binding.root)
        binding.btnIngresarDone.setOnClickListener(this)
        showDialog()
        binding.txvOlvideContrasenia.setOnClickListener(this)
    }

    private fun showDialog(){
        val dial = RecuperarContraseniaDialog()
        dial.show(supportFragmentManager, "diagprueba")
    }
    override fun onClick(v: View?) {
        when (v?.id) {
            R.id.btn_ingresar_done -> {
                val i = Intent(this, PrincipalActivity::class.java)
                startActivity(i)
            }
            R.id.txvOlvideContrasenia -> {

                showDialog()
            }
        }
    }
}
```

**Comment by fraggjkee** [comment]
Have you tried using `onCreateView` in your dialog fragment instead of calling `setView` on `AlertDialog` from `onCreateDialog`? I think the approach you use isn't quite natural for dialog fragments.

**Comment by BrandonQuintanilla** [comment]
I also have tried this.
```

class RecuperarContraseniaDialog : DialogFragment(), View.OnClickListener {

    private var _binding: DialogRecuperarContraseniaBinding? = null
    private val binding get() = _binding!!

/*    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        _binding = DialogRecuperarContraseniaBinding.inflate(LayoutInflater.from(context))
        return AlertDialog.Builder(requireActivity()).setView(binding.root).create()

    }*/

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        _binding = DialogRecuperarContraseniaBinding.inflate(inflater, container, false)
        return binding.root

    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    override fun onClick(view: View) {
        when (view.id) {
            R.id.btn_close -> {
                dismiss()
            }
            R.id.btn_registrarse_done -> {
                dismiss()
            }
        }
    }
}

```
And Added the context property at the parentView:
```

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="@drawable/dialog_rounded_corners"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    android:paddingBottom="15dp"
    tools:context=".fragments.dialogs.RecuperarContraseniaDialog">

    <ImageButton
        android:id="@+id/btn_close"
        android:layout_width="25dp"
        android:layout_height="25dp"
        android:layout_marginTop="10dp"
        android:layout_marginEnd="10dp"
        android:background="@drawable/cerrar_dialog"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/txv_descr"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:paddingHorizontal="20dp"
        android:paddingVertical="5dp"
        android:text="Ingrese el código enviado a su correo electrónico para restablecer su contraseña"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/btn_close" />

    <com.fraggjkee.smsconfirmationview.SmsConfirmationView
        android:id="@+id/code_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="15dp"
        android:background="@color/white"
        android:gravity="center"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/txv_descr"
        app:scv_codeLength="4"
        app:scv_symbolBackgroundColor="@color/white"
        app:scv_symbolBorderColor="@color/md_grey_400"
        app:scv_symbolBorderCornerRadius="6dp"
        app:scv_symbolBorderWidth="2dp"
        app:scv_symbolHeight="50dp"
        app:scv_symbolTextSize="27sp"
        app:scv_symbolWidth="45dp"
        app:scv_symbolsSpacing="5dp" />

    <Space
        android:id="@+id/space_one"
        android:layout_width="match_parent"
        android:layout_height="20dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/code_view" />

    <androidx.appcompat.widget.AppCompatButton
        android:id="@+id/btn_registrarse_done"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/primary_btn_style"
        android:paddingHorizontal="30dp"
        android:text="Restablecer su contraseña"
        android:textAllCaps="false"
        android:textColor="@color/md_white_1000"
        android:textSize="14dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/space_one" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

But there is still the same error. I know that it happes because of the SmsConfirmationView because if I comment the xml of the SmsConfirmationView view, everything works ok with any form.

![image](https://user-images.githubusercontent.com/48459532/108297831-da208080-7169-11eb-99e8-20184ebad1b4.png)

`2021-02-17 21:47:35.482 9977-9977/com.acpomotape.acpomotape E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.acpomotape.acpomotape, PID: 9977
    android.view.InflateException: Binary XML file line #36 in com.acpomotape.acpomotape:layout/dialog_recuperar_contrasenia: Binary XML file line #36 in com.acpomotape.acpomotape:layout/dialog_recuperar_contrasenia: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #36 in com.acpomotape.acpomotape:layout/dialog_recuperar_contrasenia: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at com.acpomotape.acpomotape.databinding.DialogRecuperarContraseniaBinding.inflate(DialogRecuperarContraseniaBinding.java:65)
        at com.acpomotape.acpomotape.fragments.dialogs.RecuperarContraseniaDialog.onCreateView(RecuperarContraseniaDialog.kt:26)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:482)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     **Caused by: java.lang.IllegalStateException: LifecycleOwner com.acpomotape.acpomotape.activities.LoginActivity@e7a57ff is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.**
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:116)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:653)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:662)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.registerForSmsRetrieverResult(SmsConfirmationView.kt:164)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.<init>(SmsConfirmationView.kt:68)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.<init>(SmsConfirmationView.kt:27)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.<init>(Unknown Source:6)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:852) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532) 
        at com.acpomotape.acpomotape.databinding.DialogRecuperarContraseniaBinding.inflate(DialogRecuperarContraseniaBinding.java:65) 
        at com.acpomotape.acpomotape.fragments.dialogs.RecuperarContraseniaDialog.onCreateView(RecuperarContraseniaDialog.kt:26) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950) 
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:482) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

I would  appreciate your help and obviously I may help you for replicate the exception :)

**Comment by fraggjkee** [comment]
I've managed to reproduce the issue and it seems to be unique to `DialogFragment` and its unusual lifecycle: `onAttachedToWindow` callback is invoked when the parent dialog fragment has already been moved to RESUMED state and that's different from regular `Fragment`. Unfortunately, because of this, it is not possible to do automatic SMS detection stuff, at least I didn't find any solution. So for now I just added a crash fix, your app should no longer crash but the SmsView won't automatically be listening to incoming messages. You can live with this if this automation isn't viable for your app I guess. Otherwise, you may try fixing it somehow by updating the library (feel free to raise a PR if you'll come up with a solution) OR you can simply implement SMS detection logic manually.

**Comment by BrandonQuintanilla** [comment]
I understand. I think that a boolean parameter for disable /enable the automatic sms detection would be also useful because, actually, I will send the confirmation code through e-mail(In Peru the sms is expensive) and I decided to use your repo because of the grafical flexibility. Anyway, thanks a lot for the help!

**Comment by fraggjkee** [comment]
No problem! It's a good idea to add a way to disable SMS detection, will definitely add something like this in future versions
