### ISSUE TITLE
Not working with android 14 phones

### ISSUE THREAD

**Issue by onplmobileapps** [fraggjkee/sms-confirmation-view#12]
FATAL EXCEPTION: main
                                Process: com.ls.onenetwork.mtag.debug, PID: 23833
                                java.lang.SecurityException: com.ls.onenetwork.mtag.debug: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                	at android.os.Parcel.createException(Parcel.java:3041)
                                	at android.os.Parcel.readException(Parcel.java:3024)
                                	at android.os.Parcel.readException(Parcel.java:2966)
                                	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                                	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                                	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                                	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
                                	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
                                	at com.fraggjkee.smsconfirmationview.SmsConfirmationView.startListeningForIncomingMessagesInternal(SourceFile:246)
                                	at com.fraggjkee.smsconfirmationview.SmsConfirmationView.onAttachedToWindow(SourceFile:160)
                                	at android.view.View.dispatchAttachedToWindow(View.java:21980)
                                	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
                                	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                                	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
                                	at android.view.ViewGroup.addViewInner(ViewGroup.java:5318)
                                	at android.view.ViewGroup.addView(ViewGroup.java:5104)
                                	at androidx.fragment.app.FragmentContainerView.addView(SourceFile:272)
                                	at android.view.ViewGroup.addView(ViewGroup.java:5044)
                                	at androidx.fragment.app.FragmentStateManager.addViewToContainer(SourceFile:880)
                                	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:565)
                                	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:272)
                                	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1943)
                                	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:1845)
                                	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:1782)
                                	at androidx.fragment.app.FragmentManager$5.run(SourceFile:565)
                                	at android.os.Handler.handleCallback(Handler.java:958)
                                	at android.os.Handler.dispatchMessage(Handler.java:99)
                                	at android.os.Looper.loopOnce(Looper.java:205)
                                	at android.os.Looper.loop(Looper.java:294)
                                	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                	at java.lang.reflect.Method.invoke(Native Method)
                                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                Caused by: android.os.RemoteException: Remote stack trace:
                                	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
                                	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
                                	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
                                	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                	at android.os.Binder.execTransact(Binder.java:1275)
                                
Logcat attached

**Comment by fraggjkee** [comment]
Hey, the issue should have been fixed in 1.8.1, thanks for reporting!
