### ISSUE TITLE
The app crashes

### ISSUE THREAD

**Issue by danysz** [fraggjkee/sms-confirmation-view#2]
I have an activity and the SMSConfirmationView is in a fragment.
```
    <com.fraggjkee.smsconfirmationview.SmsConfirmationView
        android:id="@+id/sms_code_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="24dp"
        app:scv_symbolHeight="56dp"
        app:scv_codeLength="6"/>
```

When I am trying to show this fragment I am getting error :

```
2021-05-06 12:06:48.767 17306-17306/com.app.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.staging, PID: 17306
    android.view.InflateException: Binary XML file line #51 in com.app.staging:layout/frg_reg_sms_code: Binary XML file line #51 in com.app.staging:layout/frg_reg_sms_code: Error inflating class com.fraggjkee.smsconfirmationview.SmsConfirmationView
    Caused by: android.view.InflateException: Binary XML file line #51 in com.app.staging:layout/frg_reg_sms_code: Error inflating class com.fraggjkee.smsconfirmationview.SmsConfirmationView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at com.app.ui.registration.FrgRegSMSCode.onCreateView(FrgRegSMSCode.kt:22)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:341)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
        at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7556)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:860)
        at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8601)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8559)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8547)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1641)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1116)
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1838)
        at androidx.recyclerview.widget.RecyclerView$SmoothScroller.onAnimation(RecyclerView.java:11920)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5390)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
        at android.view.Choreographer.doFrame(Choreographer.java:1040)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1275)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
2021-05-06 12:06:48.768 17306-17306/com.app.staging E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.IllegalStateException: LifecycleOwner com.app.ui.registration.ActRegistration@b369a59 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:123)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:659)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:668)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.registerForSmsRetrieverResult(SmsConfirmationView.kt:164)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.<init>(SmsConfirmationView.kt:68)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.<init>(SmsConfirmationView.kt:27)
        at com.fraggjkee.smsconfirmationview.SmsConfirmationView.<init>(Unknown Source:6)
        	... 43 more
```

After more research I found that the problem is related to the previous opened Issue.
The fail is happening here :
```
return registerForActivityResult(SmsRetrieverContract()) { smsContent ->
            val view = this@SmsConfirmationView
            smsContent?.takeIf { it.isBlank().not() }
                ?.let { SmsParser.parseOneTimeCode(it, view.codeLength) }
                ?.let { view.enteredCode = it }
        }
```

for the same reason. The lifecycle current state is RESUMED

**Comment by danysz** [comment]
You can create an app with basic activity (two fragments) and if you put the "SMSConfirmationView" on the second fragment it will crash when you change fragment

**Comment by fraggjkee** [comment]
> You can create an app with basic activity (two fragments) and if you put the "SMSConfirmationView" on the second fragment it will crash when you change fragment

Hmm.. looks like I'm unable to reproduce this, could you prepare a sample app or at least post some code here?

Here's what I tried:
```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        supportFragmentManager.beginTransaction()
            .add(R.id.content, FragmentA(), "fragmentA")
            .commit()

        Handler().postDelayed(
            {
                supportFragmentManager.beginTransaction()
                    .replace(R.id.content, FragmentB(), "fragmentB")
                    .commit()
            },
            1000
        )
    }
}

class FragmentA : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_a, container, false)
    }
}

class FragmentB : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_b, container, false)
    }
}
```

Both fragments contain `SmsConfirmationView`:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="24dp"
        android:layout_marginBottom="24dp"
        android:text="Fragment B" />

    <com.fraggjkee.smsconfirmationview.SmsConfirmationView
        android:id="@+id/sms_code_view"
        app:scv_codeLength="4"
        app:scv_symbolBackgroundColor="@android:color/white"
        app:scv_symbolBorderColor="@android:color/black"
        app:scv_symbolBorderCornerRadius="8dp"
        app:scv_symbolBorderWidth="2dp"
        app:scv_symbolHeight="52dp"
        app:scv_symbolTextColor="@android:color/black"
        app:scv_symbolTextSize="24sp"
        app:scv_symbolWidth="48dp"
        app:scv_symbolsSpacing="12dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal" />

</LinearLayout>
```

**Comment by fraggjkee** [comment]
I added a way to disable automatic SMS detection so you can try switching it off if you don't really need all of that, it should fix the crash.
